/* Find the names of Employees whose name occurs twice. 

listofduplicates predicate returns a list with Names that are occurring more than once. occurrence predicate takes the listofduplicates and LA that was generated by findall,
occurrence returns a list with same names packed in a List. (Example: [[Jack,Jack],[Tom]...]. 
Finally, nameoccurringtwice predicate simply uses the packed list and returns us the name which is occurring twice in the list by using length.
*/
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
employee(101,'Jack').
employee(102,'Tom').
employee(103,'Adam').
employee(104,'John').
employee(105,'Jack').
employee(106,'Adam').
employee(107,'Bob').
employee(108,'Pat').
employee(109,'Adam').
employee(110,'Joe').
employee(111,'Joe').

check(A):-
    findall(P,employee(_,P),LP),
    listofduplicates(LP,LB),
    occurrence(LB,LP,B),
    nameoccurringtwice(B,A),!.

occurrence([],_,[]).
occurrence([H|T],[H2|T2],[V|L]):-
    occurrence2(H,[H2|T2],V),
    occurrence(T,[H2|T2],L).

occurrence2(_,[],[]).
occurrence2(H,[H2|T2],[H|B]):-
    H=H2,
    occurrence2(H,T2,B).
occurrence2(H,[H2|T2],B):-
    H\=H2,
    occurrence2(H,T2,B).

listofduplicates([],[]).
listofduplicates([H|T],L):-
    \+member(H,T),
    listofduplicates(T,L).
listofduplicates([H|T],[H|L]):-
    member(H,T),
    listofduplicates(T,L).

nameoccurringtwice([],[]).
nameoccurringtwice([H|T],[Name|K]):-
    length(H,Len),
    Len=2,
    H=[Name,_],
    nameoccurringtwice(T,K).
nameoccurringtwice([H|T],K):-
    length(H,Len),
    Len\=2,
    nameoccurringtwice(T,K).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
/*Execute the Program:-
?-check(A).
OUTPUT:
A = ['Jack', 'Joe']

*/
